### ISSUE TITLE
Bidirectional brc

### ISSUE THREAD

**Issue by bratao** [niklexical/brc_pytorch#3]
@niklexical and @jannisborn , this is a very awesome and refreshing work!!

I want to test BRC on NLP tasks, and I´m wondering if you already tested or have plans of having a bidirectional BRC, as it is something that vastly improves NLP taaks.

Thanks!

**Comment by jannisborn** [comment]
Hi @bratao 
Thanks for your interest :)
We've been exclusively observing promising results comparing to standard RNN cells, especially for the nBRC. I'd be super curious to see any results on NLP, please feel free to share.

Regarding bidirectionality: We considered that but haven't actually started an implementation. Following the experiments in the BRC paper, we decided to prioritise a multi-layer variant over bidirectionality. This was not trivial since `pytorch`, unlike `tensorflow`, doesn't [have a RNN wrapper](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN).
So the bidirectionally is the obvious next step. The simplest (but certainly not fastest) option is to adapt the [`forward` method](https://github.com/niklexical/brc_pytorch/blob/8fea95bd1c49b6a4803d1183b9d41ed64e1ac9dd/brc_pytorch/layers/brc_layer.py#L49) of the cells by reverting the sequences if the boolean is set in the constructor.
That should be easy to do, so please feel free to submit a PR! :)
